name: rl4aa23-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - cheetah-accelerator
    - imageio
    - ipywidgets
    - jupyterlab
    - matplotlib
    - moviepy
    - names
    - opencv-python
    - pyyaml
    - stable-baselines3==1.5
